name: CI/CD to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/unit/test_server.py -v --cov=app --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3

  build_and_push:
    needs: unit_tests
    if: github.ref == 'refs/heads/main'  # Только для main ветки
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: |
        # Сборка образа
        docker build -t ${{ secrets.DOCKER_USERNAME }}/yourapp:latest .
        
        # Пушим с двумя тегами: latest и SHA коммита
        docker push ${{ secrets.DOCKER_USERNAME }}/yourapp:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/yourapp:latest ${{ secrets.DOCKER_HUB_USERNAME }}/yourapp:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/yourapp:${{ github.sha }}
        
      