name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_testing:
    name: "🚀 Unit Testing"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov httpx
        # Устанавливаем только то, что нужно для unit-тестов
        # SQLAlchemy не ставим, так как БД не используем

    - name: Run unit tests
      run: |
        # Игнорируем тесты, требующие БД (если нужно)
        pytest tests/ -v -k "not integration" --cov=./ --cov-report=xml --junitxml=test-results/junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'test-results/junit.xml'
        check_name: 'Unit Test Results'

    - name: Upload coverage
      uses: codecov/codecov-action@v3