name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_testing:
    name: "🚀 Unit Testing"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # Добавьте другие зависимости, если нужно

    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=./ --cov-report=xml --junitxml=test-results/junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'test-results/junit.xml'
        check_name: 'Unit Test Results'
        annotate_only: true

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: success()

    - name: Show summary
      if: always()
      run: |
        echo "✅ Unit tests completed!"
        echo "View coverage report in Codecov"